### ISSUE TITLE
Total budget showing as 0 €

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#209]
https://kohesio.eu/beneficiaries?fund=ERDF---European-Regional-Development-Fund&country=France&region=Provence-Alpes-C%C3%B4te-d%27Azur

"Métropole d'Aix-Marseille-Provence" for instance shows a total budget of 0 € even though several projects linked to this beneficiary have a total budget filled: https://kohesio.eu/beneficiaries/Q2536086

**Comment by madewild** [comment]
default value should be Unknown

**Comment by raphdom** [comment]
@AlyHdr can you give me an example that we have empty in the budget for a beneficiary that I can test?

**Comment by AlyHdr** [comment]
Here some of the fields should be n/a or something instead of blank like the row : "Métropole d'Aix-Marseille-Provence"

https://dev.kohesio.eu/beneficiaries?country=France&region=Provence-Alpes-C%C3%B4te-d%27Azur&fund=ERDF---European-Regional-Development-Fund

<img width="1772" alt="Screenshot 2021-06-22 at 19 30 41" src="https://user-images.githubusercontent.com/43681203/122972365-592ffa80-d390-11eb-8993-f23a001548f3.png">

**Comment by raphdom** [comment]
fixed on dev. can you check please? @AlyHdr

**Comment by AlyHdr** [comment]
Yes this looks fine for me we can close the issue.

**Comment by madewild** [comment]
@raphdom we still have the blanks in the list below the map on https://dev.kohesio.eu/beneficiaries/Q2536086 for instance

**Comment by AlyHdr** [comment]
Yes Max is right and I checked actually the API is returning a missing field "budget" in case there is no total budget, @raphdom do you prefer that we return an empty value with the budget existing ?

**Comment by raphdom** [comment]
@AlyHdr. it is not necessary. I manage to put unknown when we don't have the field, thanks! it will be deployed on dev in 5min

**Comment by raphdom** [comment]
@AlyHdr @madewild fixed on dev, you can test, please

**Comment by madewild** [comment]
fine for me
