### ISSUE TITLE
Reframing EU North

### ISSUE THREAD

**Issue by madewild** [ec-doris/kohesio.eu#330]
Can we slightly change the default coordinates of the map (max latitude) so that Sweden and Finland are shown in full when first loading the page? Currently they are slighly cut in the North:
![se-fi](https://user-images.githubusercontent.com/942488/152134917-70563335-ea2d-444d-bee8-5ffc7da920ec.png)

Request of REGIO map unit...

**Comment by madewild** [comment]
or maybe this is coming from the backend @D063520 ?

**Comment by D063520** [comment]
no, it is not coming form the backend .... it is hard coded in the ui

**Comment by raphdom** [comment]
yes, I will change it

**Comment by raphdom** [comment]
done, can you check please?

**Comment by madewild** [comment]
For me it still appears slightly cut :/
![cut](https://user-images.githubusercontent.com/942488/152300052-57d13de5-0edc-46bc-a405-b50cdb91e0a1.png)

**Comment by raphdom** [comment]
it is, but if I put more we will cut in the south

**Comment by madewild** [comment]
mmmh annoying, and we cannot zoom out very slightly (without making it very small)?

**Comment by madewild** [comment]
Full comment of REGIO: "The entry view of the map shows a very wide frame covering areas that are not relevant for the EU (Greenland, Kyrgyzstan…) while the northern part of the EU is missing. Our suggestion is to use a frame that is less wide and that ensures that the whole north/south extent of continental Europe is visible (i.e. from northern SE + FI to CY, Ceuta and Melilla).

Maybe we can change the height of the map?

**Comment by raphdom** [comment]
no, because the zoom has levels. Another solution could be increase the height of the map. But the right size will be 725px it is too big for small screens:
<img width="1239" alt="Screenshot 2022-02-03 at 08 56 36" src="https://user-images.githubusercontent.com/5124917/152302886-c9f408cd-b0e7-417f-ac91-be47f1a2dcbe.png">

**Comment by raphdom** [comment]
https://www.browserstack.com/guide/ideal-screen-sizes-for-responsive-design#:~:text=According%20to%20the%20Worldwide%20Screen,360%C3%97640%20(7.28%25)

I think it will be fine to go to 725px. What do you think?

**Comment by madewild** [comment]
ok let's test!

**Comment by raphdom** [comment]
done, you can test

**Comment by madewild** [comment]
Much better! Maybe we can save some space between the carousel and "in my region" to compensate? (orange zone)
![orange2](https://user-images.githubusercontent.com/942488/152307921-08d2dfb1-fcb1-469b-a98a-45444cef4a8b.png)

**Comment by raphdom** [comment]
I will tell @omar0z  to change the margin in home component (change class mt-5 to mt-2), to avoid to touch in the same file... then you can close this @madewild
